[package]
name = "anyhow-http-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
http.workspace = true

darling = "0.20"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
